AllCops:
  Exclude:
    - 'rails-settings-cached-typed.gemspec'
    - 'vendor/**/*'
    - 'lib/generators/settings/templates/*'

Documentation:
  Enabled: false

# don't prefer 'fail' over raise
SignalException:
  Enabled: false

LineLength:
  Max: 115

ClassVars:
  Enabled: false

FileName:
  Enabled: false

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
